name: "Bicep Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/**"
      - ".github/workflows/*bicep*.yml"

jobs:
  bicep-deploy-dev:
    name: Bicep Deploy Dev
    uses: ./.github/workflows/step-bicep-deploy.yml
    with:
      env: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMINISTRATOR_LOGIN: ${{ secrets.POSTGRES_USERNAME_DEV }}
      ADMINISTRATOR_LOGIN_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_DEV }}

  bicep-deploy-prod:
    name: Bicep Deploy Prod
    uses: ./.github/workflows/step-bicep-deploy.yml
    needs: bicep-deploy-dev
    with:
      ENV: prod
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMINISTRATOR_LOGIN: ${{ secrets.POSTGRES_USERNAME_PROD }}
      ADMINISTRATOR_LOGIN_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_PROD }}
