name: "Flyway PR"

on:
  pull_request:
    branches:
      - main
    paths:
      - "sql/**"
      - ".github/workflows/*flyway*.yml"

jobs:
  flyway-pr-dev:
    name: Flyway PR Verify
    uses: ./.github/workflows/step-flyway-pr-verify.yml
    with:
      env: dev
    secrets:
      postgres_username: ${{ secrets.POSTGRES_USERNAME_DEV }}
      postgres_password: ${{ secrets.POSTGRES_PASSWORD_DEV }}
      postgres_url: ${{ secrets.POSTGRES_URL_DEV }}
