name: "Step - Flyway PR Verify"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  flyway-migrate:
    name: Flyway Migrate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1.0.0

      - name: Flyway validate
        run: >
          docker run -v $(pwd)/sql/:/flyway/sql flyway/flyway:9.22-alpine
          -url=jdbc:postgresql://db:5432/a_site_to_order_stuff?sslmode=require
          -user=postgres
          -password=postgres
          -connectRetries=1
          -validateMigrationNaming=true
          -ignoreMigrationPatterns='*:pending'
          validate

      - name: Flyway migrate
        run: >
          docker compose up --force-recreate -d && sleep 5 && docker compose logs && docker compose logs | (! grep ERROR &>/dev/null)
